### ISSUE TITLE
README is missing the build process for *_notrunc.sto

### ISSUE THREAD

**Issue by Gallo13th** [Shunsuke-1994/rfamgen#1]
Here is my running log, thanks for you reply

```bash
 python scripts/get_tidy_sequences_from_fasta_rfam.py --seed_file ./datasets/Rfam.seed --rfam RF00167 --output_dir datasets/RF00167 --cpu 1
```
```
Total number            :  2660
After uniquenize        :  2603
created datasets/RF00167/RF00167_unique.fa
seed_seq                : 133
all_seq                 : 2571
full_seq - seed_seq     : 2436
```
```bash
 python scripts/make_onehot_from_traceback.py --fasta datasets/RF00167/RF00167_unique_seed_removed.fa --cmfile ./datasets/RF00234/RF00167.cm --cpu 1
```
```
cmalign --cpu 1   --notrunc  --sfile datasets/RF00167/RF00167_unique_seed_removed_notrunc_score.txt --tfile datasets/RF00167/RF00167_unique_seed_removed_notrunc_traceback.txt --ifile datasets/RF00167/RF00167_unique_seed_removed_notrunc_insertion.txt --elfile datasets/RF00167/RF00167_unique_seed_removed_notrunc_ELstate.txt ./datasets/RF00234/RF00167.cm datasets/RF00167/RF00167_unique_seed_removed.fa > datasets/RF00167/RF00167_unique_seed_removed_notrunc_tmp.sto
gzip datasets/RF00167/RF00167_unique_seed_removed_notrunc_traceback.txt
gzip: datasets/RF00167/RF00167_unique_seed_removed_notrunc_traceback.txt: No such file or directory
esl-reformat --informat stockholm -o datasets/RF00167/RF00167_unique_seed_removed_notrunc.sto stockholm datasets/RF00167/RF00167_unique_seed_removed_notrunc_tmp.sto
/bin/sh: 1: esl-reformat: not found
Traceback (most recent call last):
  File "/home/letgao/RNAdesign/rfamgen/scripts/make_onehot_from_traceback.py", line 72, in <module>
    preprocess.cmalign(
  File "/home/letgao/RNAdesign/rfamgen/src/preprocess.py", line 79, in cmalign
    alignment = AlignIO.read(outstk, "stockholm")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/letgao/miniconda3/envs/rfamgen/lib/python3.11/site-packages/Bio/AlignIO/__init__.py", line 440, in read
    alignment = next(iterator)
                ^^^^^^^^^^^^^^
  File "/home/letgao/miniconda3/envs/rfamgen/lib/python3.11/site-packages/Bio/AlignIO/__init__.py", line 366, in parse
    with as_handle(handle) as fp:
  File "/home/letgao/miniconda3/envs/rfamgen/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/letgao/miniconda3/envs/rfamgen/lib/python3.11/site-packages/Bio/File.py", line 71, in as_handle
    with open(handleish, mode, **kwargs) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/RF00167/RF00167_unique_seed_removed_notrunc.sto'
```

**Comment by Shunsuke-1994** [comment]
Have you resolved the issue?

Shunsuke

**Comment by Gallo13th** [comment]
> Have you resolved the issue?
> 
> Shunsuke

yes, thanks for reply. I generated the corresponding files myself according to the standard infernal process, and you may still need to consider updating the README, e.g. the .sto file can be fetched from Rfam, and you may need to indicate which files should be provided before the script runs. All in all, thank you for your great work, though.

**Comment by Shunsuke-1994** [comment]
I appreciated your comment. I will update README soon.

Best, 
Shunsuke
